version: "3.8"

networks:
  oni:
    name: oni
    driver: bridge

services:
  db:
    image: postgres:13-alpine
    hostname: db
    tty: true
    environment:
      TERM: "xterm-256color"
      NODE_ENV: "production"
      POSTGRES_DB: "oni"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /postgresql/data
    # volumes:
    #     - describo_online_db_test:/postgresql
    ports:
      - "5432:5432"

  api:
    image: arkisto/oni-api
    hostname: api
    tty: true
    environment:
      TERM: "xterm-256color"
      NODE_ENV: "production"
      LOG_LEVEL: "debug"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_DATABASE: "oni"
    volumes:
      - ./configuration/configuration.json:/srv/configuration.json
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - /opt/storage/oni:/opt/storage/oni
    ports:
      - "8080:8080"
    command: ["/wait-for-it.sh", "db:5432", "-t", "20", "elasticsearch:9200", "-t", "20", "--", "node", "./server.bundle.js"]

  ui:
    image: arkisto/oni-ui:latest
    hostname: ui
    tty: true
    environment:
      ASSET_PATH: "http://localhost:9000/"
      TITLE: "Oni"
      TERM: "xterm-256color"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "app:8080", "-t", "10", "--", "nginx", "-g", "daemon off;"]
    ports:
      - "9000:9000"

  elasticsearch:
    image: elasticsearch:7.14.2
    hostname: elasticsearch
    tty: true
    environment:
      TERM: "xterm-256color"
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
