version: "3.8"

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "oni"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: ""
            POSTGRES_HOST_AUTH_METHOD: "trust"
            PGDATA: /postgresql/data
        # volumes:
        #     - describo_online_db_test:/postgresql
        ports:
            - "5432:5432"


