version: "3.8"

networks:
    oni:
        name: oni
        driver: bridge

volumes:
    postgres_data:
    opensearch_data:

services:
    db:
        image: postgres:16-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "oni"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: ""
            POSTGRES_HOST_AUTH_METHOD: "trust"
            PGDATA: /postgresql/data
        volumes:
             - postgres_data:/postgresql
        ports:
          - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d oni"]
            interval: 30s
            timeout: 10s
            retries: 5

    api:
        #image: node:22-alpine
        image: oni
        build: 
            context: .
            dockerfile: Dev.Dockerfile
        depends_on:
            db:
                condition: service_healthy
            opensearch:
                condition: service_healthy
        user: "1000:1000"
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            LOG_LEVEL: "debug"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "root"
            DB_PASSWORD: ""
            DB_DATABASE: "oni"
            SEARCH_HOST: "opensearch"
        volumes:    
            - .:/srv:delegated
            # - ./{NODE_ENV}-configuration:/srv/configuration
            - /opt/storage/oni:/opt/storage/oni
        working_dir: /srv
        command: ["npm", "run", "dev:docker"]
        ports:
            - "8080:8080"
            - "9229:9229"

    opensearch:
        image: opensearchproject/opensearch:2.13.0
        hostname: opensearch
        tty: true
        environment:
            - TERM="xterm-256color"
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms2g -Xmx2g
            #- xpack.security.enabled=false # for elasticsearch
            - plugins.security.disabled=true # for opensearch
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ASd8asfhqu2i3r@#$1546
        volumes:
             - opensearch_data:/usr/share/opensearch/data    
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
