version: "3.8"

networks:
    oni:
        name: oni
        driver: bridge

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "oni"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: ""
            POSTGRES_HOST_AUTH_METHOD: "trust"
            PGDATA: /postgresql/data
        # volumes:
        #     - describo_online_db_test:/postgresql
        ports:
          - "5432:5432"

    api:
        #image: node:18-buster
        build: api
        user: "1000:1000"
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            LOG_LEVEL: "debug"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "root"
            DB_PASSWORD: ""
            DB_DATABASE: "oni"
        volumes:
            #- api_node_modules:/srv/api/node_modules:delegated
            - ./api:/srv/api:delegated
            - ./.git:/srv/api/.git:delegated
            - ./scripts/wait-for-it.sh:/wait-for-it.sh
            - ./configuration:/srv/configuration
            - /opt/storage/oni:/opt/storage/oni
        working_dir: /srv/api
        command: ["/wait-for-it.sh", "db:5432", "elasticsearch:9200", "--", "npm", "run", "develop"]
        ports:
            - "8080:8080"
            - "9229:9229"

    elasticsearch:
        image: elasticsearch:7.14.2
        hostname: elasticsearch
        tty: true
        environment:
            TERM: "xterm-256color"
            discovery.type: "single-node"
        ports:
            - "9200:9200"
            - "9300:9300"
