version: "3.8"
name: oni

networks:
    oni:
        name: oni
        driver: bridge

volumes:
    postgres_data:
    opensearch_data:

services:
    db:
        image: postgres:16-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "oni"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: ""
            POSTGRES_HOST_AUTH_METHOD: "trust"
            PGDATA: /postgresql/data
        volumes:
             - postgres_data:/postgresql
        ports:
          - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-q"]
            interval: 30s
            timeout: 10s
            retries: 5

    opensearch:
        image: opensearchproject/opensearch:2.13.0
        hostname: opensearch
        tty: true
        environment:
            - TERM="xterm-256color"
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms2g -Xmx2g
            - _JAVA_OPTIONS=-XX:UseSVE=0 #this fixes Mac M4 bug
            #- xpack.security.enabled=false # for elasticsearch
            - plugins.security.disabled=true # for opensearch
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ASd8asfhqu2i3r@#$1546
        volumes:
             - opensearch_data:/usr/share/opensearch/data    
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
