#!/bin/bash

# Autobuild the Image on Docker Hub with advanced options and buildx for multiarch images
# Copied by moisbo from: https://github.com/Tob1asDocker/dockerhubhooksexample

# '--push' shorthand for '--output=type=registry'

set -ex

echo "### RUN build START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64"}"
echo "Architectures=${BUILDPLATFORM}"

docker buildx create --name multiarch --use
docker buildx build \
--tag "rrkive/oni:${DOCKER_TAG}" \
--platform "${BUILDPLATFORM}" \
--file "${DOCKERFILE_PATH}" \
--push .

echo "### RUN build END"
